### ISSUE TITLE
[Bug] Torch door

### ISSUE THREAD

**Issue by SylisMC** [alex5nader/Framity#13]
Can put torches(wall torches) on doors (vanilla or mod torches)
break when opening door

**Comment by alex5nader** [comment]
I just checked and this is actually vanilla behavior. You can place regular torches on regular doors and they'll break when the door is opened. 

https://user-images.githubusercontent.com/23281246/103070857-0794e780-4588-11eb-8ac8-3aaa2d1e4657.mp4

**Comment by SylisMC** [comment]
weird, it didn't do it for me when I tried?
