### ISSUE TITLE
[Suggestion] Few block requests

### ISSUE THREAD

**Issue by SylisMC** [alex5nader/Framity#20]
Firstly, good work with this mod, you did a great job and i shall be enjoying this mod for sometime

You may already have plans for some of these but it might be nice to have a few extra blocks if you see fit.

* Walls
* Snow layers
* Slopes
* Arches
* Scaffold
* Ladders
* Carpet
* Iron Bars
* Signs
* Chains

* For immersion, it may be nice to have blocks assume the same sounds when being walking on

As always, Thanks for the hard work and dedication!

**Comment by alex5nader** [comment]
Hey, thanks for the kind words! I like the suggestions, and I've copied them onto the general roadmap [here](https://github.com/alex5nader/Framed/projects/1). I'm not sure what exactly you mean by arches, though. If you have an image or vanilla block that I'm forgetting that'd be great.

**Comment by SylisMC** [comment]
> Hey, thanks for the kind words! I like the suggestions, and I've copied them onto the general roadmap [here](https://github.com/alex5nader/Framed/projects/1). I'm not sure what exactly you mean by arches, though. If you have an image or vanilla block that I'm forgetting that'd be great.

Arches are a little bit of a stretch from vanilla, some carpenters blocks like mods had arches
![635612450508267495](https://user-images.githubusercontent.com/19602662/103311142-91f5a500-49e7-11eb-8775-38c1935dba66.png)

**Comment by milkev** [comment]
I would like to suggest one more:
an Anvil frame block, it wouldnt be functional, obviously, but even the base anvil makes its way into builds for aesthetic purposes.
