### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by TheRealM18** [alex5nader/Framity#25]
With Version 1.0.1, there is a lot of missing, either textures, or json files.  This is a quick fix, and would take about max 1 hour, but not a massive bug.

![image](https://user-images.githubusercontent.com/5025664/104376792-e7f43d80-54fb-11eb-8f13-0e3f88d1c335.png)

**Comment by alex5nader** [comment]
Hey, could you attach your game's log? I don't get this issue on my end, with or without REI.

**Comment by TheRealM18** [comment]
Im not sure which mod is doing it, but there is a render issue with one of them that causes that.... I'll help find the one, but here is a list of all of them that I'm testing.

https://pastebin.com/dRNRBvdx

**Comment by TheRealM18** [comment]
Found it, after a few launches... It is a conflict between Framed, and Sodium somewhere.

**Comment by alex5nader** [comment]
The error is because of Sodium. Framed uses the Fabric Rendering API, but Sodium has not implemented support for it yet. It’s planned for Sodium 0.2. This is not something I’m able to fix.
