### ISSUE TITLE
Why is this mod incompatable with Sodium

### ISSUE THREAD

**Issue by nullified33** [alex5nader/Framity#31]

**Comment by alex5nader** [comment]
Framed makes heavy use of the Fabric Rendering API, which Sodium currently does not support. Once Sodium updates to support this, Framed should work fine with it. There's nothing I can do on my end to make it work.

**Comment by nullified33** [comment]
> Framed makes heavy use of the Fabric Rendering API, which Sodium currently does not support. Once Sodium updates to support this, Framed should work fine with it. There's nothing I can do on my end to make it work.

Have you heard of indium?

**Comment by nullified33** [comment]
> > Framed makes heavy use of the Fabric Rendering API, which Sodium currently does not support. Once Sodium updates to support this, Framed should work fine with it. There's nothing I can do on my end to make it work.
> 
> Have you heard of indium?

Basically frapi for sodium

**Comment by alex5nader** [comment]
Yes, I've heard of Indium. I only list Sodium as a conflict and not a break in case it works. If Framed doesn't work under Indium, it's likely because Indium is still a work in progress.

**Comment by nullified33** [comment]
> Yes, I've heard of Indium. I only list Sodium as a conflict and not a break in case it works. If Framed doesn't work under Indium, it's likely because Indium is still a work in progress.

Ill tell u if it works

**Comment by nullified33** [comment]
> Yes, I've heard of Indium. I only list Sodium as a conflict and not a break in case it works. If Framed doesn't work under Indium, it's likely because Indium is still a work in progress.

Works with indium
